# Project Name: Aixt, https://github.com/fermarsan/aixt.git
# Author: Fernando Mart√≠nez Santa
# Date: 2023
# License: MIT
#
# Description: Setup file for the Emulator port. It works on Linux and Windows 
#              PCs and on Android with Termux
port =    "Emulator" 
device =  "Emulator"
board =   "Software Emulator"
backend = "c"

cc_linux =   "gcc"
cc_windows = "c:\\v\\thirdparty\\tcc\\tcc.exe"
cc_flags =   "-o"

path = "Emulator"

fixed_size_arrays  = "true"
array_default_len  = 20

fixed_size_strings = "true"
string_default_len = 80

void =  "void"
bool =  "bool"

i8 =    "signed char"
i16 =   "short"
int =   "long"
i64 =   "long long"
isize = "long long"
int_literal = "long"

u8 =    "unsigned char"
u16 =   "unsigned short"
u32 =   "unsigned long"
u64 =   "unsigned long long"
usize = "unsigned long long"

f32 = "float"
f64 = "double"
float_literal = "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = "int"
main_params =   ""   

api_modules = [
    "pin",
    "adc",
    "pwm",
    "uart",
    "time"
]

[aliases]

