# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# Authors: Carlos Zapata , Anderson Marin
# Date: 2024
# License: MIT
#
# Description: This is the setup file for the XIAO-SAMD21 board

port = "XIAO-SAMD21"
device = "SAMD21"
board = "Seeed Studio XIAO SAMD21"
backend = "arduino"

cc_linux =      "Arduino CLI"
cc_windows =    "C:\\Users\\Alexa\\AppData\\Local\\Programs\\Arduino IDE"
cc_flags =      "-o"


path="Seeed-Studio/XIAO-SAMD21"  


fixed_size_arrays  = "true"
array_default_len  = 20

fixed_size_strings = "true"
string_default_len = 80

void =  "void"
bool =  "bool"

i8 =    "int8_t"
i16 =   "int16_t"
int =   "int32_t"
i64 =   "int64_t"
isize = "int32_t"
int_literal = "int32_t"

u8 =    "uint8_t"
u16 =   "uint16_t"
u32 =   "uint32_t"
u64 =   "uint64_t"
usize = "uint32_t"

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = "int"
main_params =   "void"   

api_modules = [
    "pin",
    "time",
    "adc",
    "pwm",
    "uart"
]

[aliases]