# This file is part of the Aixt project, https://gitlab.com/fermarsan/aixt-project.git
#
# The MIT License (MIT)
# 
# Copyright (c) 2023 Fernando Mart√≠nez Santa 

device =  "x64"
board =   "PC"

cc_linux =      "gcc"
cc_windows =    "c:\\v\\thirdparty\\tcc\\tcc.exe"
aixt_api =      "./api/" 
aixt_builder =  "../../../aixtlib/builder/cembuilder/cembuilder.v"

i8 =    "signed char"
i16 =   "short"
i32 =   "long"
i64 =   "long long"
isize = "long long"
int =   "long"

u8 =    "unsigned char"
u16 =   "unsigned short"
u32 =   "unsigned long"
u64 =   "unsigned long long"
usize = "unsigned long long"

f32 =   "float"
f64 =   "double"

default_int =   "int"
default_float = "float"

mutex = "NOT SUPPORTED"
main_ret_type = "int"
main_params =   "none"   

api_modules =   []
  
headers =   []

macros =    []

config_operator =   []

configuration = []

initialization =    []

nxc =   false